---
- name: ensure destination directory exists
  file: path={{ prefix }} owner={{ ansible_user }} group=www state=directory
  sudo: yes

- name: check out jasperreports-server source
  git: repo=git@github.com:osufst/jasperreports-server-playbook.git dest={{ prefix }} version={{ jasperreports_server_version }} accept_hostkey=true
  notify:
    - restart jasperreports-server

- name: download Jasper Server CE Installer
  get_url: url=http://sourceforge.net/projects/jasperserver/files/JasperServer/JasperReports%20Server%20Community%20Edition%206.0.1/jasperreports-server-cp-6.0.1-linux-x64-installer.run/download
            dest={{ prefix }}/jasper-server-ce-installer.run validate_certs=no

- name: add permission to execute Jasper Server CE Installer
  file: path={{ prefix }}/jasper-server-ce-installer.run mode=0755

- name: run the Jasper Server CE Installer
  script: ../files/jasper_setup_expect.sh creates={{ prefix }}/jasperreports-server-cp-6.0.1/ctlscript.sh

- name: edit the startup script for Tomcat so it detaches from tty properly
  lineinfile: dest={{ prefix }}/jasperreports-server-cp-6.0.1/apache-tomcat/scripts/ctl.sh regexp="\$TOMCAT_BINDIR/startup.sh" line="nohup $TOMCAT_BINDIR/startup.sh" backrefs=yes

- name: start/restart the Jasper Server
  command: ./ctlscript.sh restart chdir=/opt/jasperreports-server-cp-6.0.1



